apiVersion: v1
kind: Service
metadata:
  name: gitops-foundations
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: ray0203
  namespace: flux-exercise
spec:
  type: LoadBalancer
  selector:
    app: gitops-foundations 
  ports:
    - port: 80
      targetPort: 8080
